# Python CircleCI 2.1 configuration file
version: 2.1

jobs:
  test:
    parameters:
      python_version:
        type: string
        default: "3.6"
    working_directory: ~/glide
    docker:
      - image: "circleci/python:<< parameters.python_version >>"
      #- image: "circleci/redis:5.0.8"
    steps:
      - checkout
      #- run:
      #    name: Wait for Redis
      #    command: dockerize -wait tcp://localhost:6379 -timeout 1m
      - run: pip install glide[complete]
      - run: pip install -r requirements.txt
      # Some tests are skipped for now to simplify configuration
      - run: GLIDE_CONFIG_FILE=$HOME/glide/tests/test_config.ini pytest --ignore=rq_ext/ --ignore=celery_ext/ -k "not email and not mysql"

workflows:
  main:
    jobs:
      - test:
          name: "Python 3.6"
          python_version: "3.6"
      - test:
          name: "Python 3.7"
          python_version: "3.7"
      - test:
          name: "Python 3.8"
          python_version: "3.8"
