# Python CircleCI 2.1 configuration file
version: 2.1

jobs:
  test:
    parameters:
      python_version:
        type: string
        default: "3.6"
    working_directory: ~/glide
    docker:
      - image: "python:<< parameters.python_version >>"
    steps:
      - checkout
      - run: pip install glide[complete]
      - run: pip install -r requirements.txt
      - run: pytest -k "not email and not mysql and not rq"

workflows:
  main:
    jobs:
      - test:
          name: "Python 3.6"
          python_version: "3.6"
      - test:
          name: "Python 3.7"
          python_version: "3.7"
      - test:
          name: "Python 3.8"
          python_version: "3.8"
